services:
  traefik:
    image: traefik:3.0.0-beta5
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme:/etc/traefik/acme # Optional: If using ACME certificates, keep this volume for certificate storage
    environment:
      DO_AUTH_TOKEN: ${DOCKER_TOKEN}
    labels:
      traefik.enable: true

  restapi:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
    container_name: restapi
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      PRODUCTION: ${PRODUCTION}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      TOKEN_EXPIRATION_TIME: ${TOKEN_EXPIRATION_TIME}
      TOKEN_ISSUER: ${TOKEN_ISSUER}
      TOKEN_AUDIENCE: ${TOKEN_AUDIENCE}
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
      DOCKER_TAG: ${DOCKER_TAG}
    labels:
      traefik.enable: true

  db:
    image: postgres:15.3-alpine3.18
    container_name: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    labels:
      # Watchtower configuration
      com.centurylinklabs.watchtower.enable: "false" # disables Watchtower for this container
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
